import {GridRowsProp} from '@mui/x-data-grid';
import {
    randomCreatedDate,
    randomTraderName,
    randomId,
  } from '@mui/x-data-grid-generator';
  
export const initialRows: GridRowsProp = [
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 25,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"NW51 STY",
      owhatnumber:randomTraderName(),
      remind:"1/1",
      dateCreated: randomCreatedDate(),
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 36,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"P3 FIX",
      owhatnumber:randomTraderName(),
      remind:"1/1",
      dateCreated: randomCreatedDate(),
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 19,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"SUF 123X",
      owhatnumber:randomTraderName(),
      remind:"1/1",
      dateCreated: randomCreatedDate(),
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 28,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"4 REG",
      owhatnumber:randomTraderName(),
      remind:"1/1",
      dateCreated: randomCreatedDate(),
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 23,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"LCH 3712",
      owhatnumber:randomTraderName(),
      remind:"1/1",
      dateCreated: randomCreatedDate(),
    },
  ];