import {GridRowsProp} from '@mui/x-data-grid';
import {
    randomCreatedDate,
    randomTraderName,
    randomId,
  } from '@mui/x-data-grid-generator';
  
export const formatRows: GridRowsProp= [];
export const initialRows: GridRowsProp = [
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 25,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"NW51 STY",
      owhatnumber:randomTraderName(),
      remind:"4/4",
      dateCreated: randomCreatedDate(),
      flag:"new",
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 36,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"P3 FIX",
      owhatnumber:randomTraderName(),
      remind:"4/5",
      dateCreated: randomCreatedDate(),
      flag:"check",
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 19,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"SUF 123X",
      owhatnumber:randomTraderName(),
      remind:"2/2",
      dateCreated: randomCreatedDate(),
      flag:"fine",
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 28,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"4 REG",
      owhatnumber:randomTraderName(),
      remind:"3/3",
      dateCreated: randomCreatedDate(),
      flag:"paid",
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 23,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"LCH 3712",
      owhatnumber:randomTraderName(),
      remind:"2/3",
      dateCreated: randomCreatedDate(),
      flag:"trash",
    },
    {
      id: randomId(),
      rname: randomTraderName(),
      fine: 44,
      rwhatnumber:randomTraderName(),
      gps:"41.40338, 2.17403",
      carnumber:"PR 453",
      owhatnumber:randomTraderName(),
      remind:"1/2",
      dateCreated: randomCreatedDate(),
      flag:"cancel",
    },
  ];