import React from "react";
import Head from 'next/head'
import PropTypes, { InferProps } from "prop-types";
import styles from '../styles/Home.module.css'



export default function Auth({children}:InferProps<typeof Auth.propTypes>){

    const [mobileOpen, setMobileOpen] = React.useState(false);

    const handleDrawerToggle = () => {
      setMobileOpen(!mobileOpen);
    };

    return(
        <div className={styles.container}>
        <Head>
          <title>Mujiba</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            {children}
        </main>
        </div>
    )
}

Auth.propTypes = {
    children: PropTypes.oneOfType([
        PropTypes.arrayOf(PropTypes.node),
        PropTypes.node
    ]).isRequired
}