import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/router";



import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import InputIcon from '@mui/icons-material/Input';
import AppRegistrationIcon from '@mui/icons-material/AppRegistration';

import styles from '../styles/Home.module.css'

export default function Home() {

  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Mujiba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mujiba
        </h1>
        <Box
          component="form"
          sx={{
            '& > :not(style)': { m: 4, width: '300px' },
          }}
          noValidate
          autoComplete="off"
        >
          <Button className={styles.logobutton} onClick={()=>router.push('/auth/login')} variant="contained" endIcon={<InputIcon />}>
            Login 
          </Button>
          <Button className={styles.logobutton} onClick={()=>router.push('/auth/register')} variant="contained" endIcon={<AppRegistrationIcon />}>
            Register 
          </Button>
        </Box>
      </main>
    </div>
  )
}
