import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/router";



import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import InputIcon from '@mui/icons-material/Input';

import styles from '../styles/Home.module.css'

export default function Home() {

  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Mujiba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mujiba
        </h1>
        <Box
          component="form"
          sx={{
             m: 4, 
             width: '300px',
          }}
          noValidate
          autoComplete="off"
        >
          <TextField className={styles.logininput} id="user-name" label="User Name"  variant="filled" />
          <TextField className={styles.logininput} id="user-password" label="Password" type="password" variant="filled" />
          <Button className={styles.loginbutton} onClick={()=>router.push('/admin/dashboard/all')} variant="contained" endIcon={<InputIcon />}>
            Login 
          </Button>
        </Box>
      </main>
    </div>
  )
}
